image: node:latest

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build

pages:
  stage: deploy
  script:
    - cp -r build public
  artifacts:
    paths:
      - public
  only:
    - main
